# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default='neighbourhood', on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood',
            field=models.CharField(default='neighbourhood', max_length=100),
        ),
    ]
