# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_auto_20190914_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood',
            field=models.CharField(max_length=100),
        ),
    ]
