# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_auto_20190914_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_location',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
        ),
    ]
