# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0007_auto_20200128_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulter',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
