# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-28 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0008_auto_20200128_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulter',
            name='house',
        ),
        migrations.AddField(
            model_name='defaulter',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Business'),
        ),
    ]
