# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-14 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0008_auto_20190914_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
    ]
