# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0009_remove_profile_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.IntegerField(),
        ),
    ]
