# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-31 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0009_auto_20200129_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulter',
            name='n_o_k_name',
        ),
        migrations.RemoveField(
            model_name='defaulter',
            name='n_o_k_phone_number',
        ),
        migrations.RemoveField(
            model_name='defaulter',
            name='post',
        ),
        migrations.AddField(
            model_name='defaulter',
            name='Next_Of_Kin_Name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='defaulter',
            name='Next_Of_Kin_Phone_Number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='defaulter',
            name='comments',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
