# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-14 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0010_auto_20190914_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='neighbourhood',
        ),
    ]
