# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0010_auto_20200131_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='contact',
            field=models.CharField(max_length=12),
        ),
    ]
